/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_imgprocesadondk_ImgProcesadoNDK */

#ifndef _Included_com_imgprocesadondk_ImgProcesadoNDK
#define _Included_com_imgprocesadondk_ImgProcesadoNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_imgprocesadondk_ImgProcesadoNDK
 * Method:    convertirGrises
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_imgprocesadondk_ImgProcesadoNDK_convertirGrises
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
